### ISSUE TITLE
ImportError: cannot import name Enviroment

### ISSUE THREAD

**Issue by TopKeingt** [synhack/mercure#65]
Internal Server Error: /en/accounts/login/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 84, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 68, in resolve_template
    return get_template(template, using=self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 18, in get_template
    engines = _engine_list(using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 72, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "/usr/local/lib/python2.7/dist-packages/django/template/utils.py", line 89, in all
    return [self[alias] for alias in self]
  File "/usr/local/lib/python2.7/dist-packages/django/template/utils.py", line 80, in __getitem__
    engine = engine_cls(params)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/jinja2.py", line 27, in __init__
    environment_cls = import_string(environment)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/Private/test/mercure/mercure/jinja2.py", line 6, in <module>
    from jinja2 import Environment
ImportError: cannot import name Environment

**Comment by treemo** [comment]
Hello!

Python3 is required (go to readme for details) ;)

**Comment by y0no** [comment]
You can use docker if you want to deploy Mercure easily and quickly
As treemo said, you need to use python3 to get mercure working on your workstation. I recommand you to use virtualenv or something like that when testing python projects like this one.

We are waiting to hear from you before closing this issue.

**Comment by TopKeingt** [comment]
ok thanks

**Comment by TopKeingt** [comment]
I just found out that you guys did miss something when you said python3 
as in [main page ](https://hub.docker.com/r/synhackfr/mercure/) said 
Git Quickstart
Requirements
   python3
   pip
Deployment
   git clone git@bitbucket.org:synhack/mercure.git && cd mercure
   pip install -r requirements.txt
   ./manage.py makemigrations
   ./manage.py migrate
   ./manage.py collectstatic
   ./manage.py createsuperuser
   ./manage.py runserver
then why you use pip instead of not pip3 ?

**Comment by y0no** [comment]
Because when you use a distribution like Archlinux, Gentoo, etc... Python3 is the default python version. So pip is just pip and pip for python2 is pip2. In addition, when you use virtualenv, pip binary is just pip even for python3
